### ISSUE TITLE
Doesn't build with Linux 5.8

### ISSUE THREAD

**Issue by felixonmars** [pgiri/ndiswrapper#6]
I cannot find a way to allocate PAGE_KERNEL_EXEC anymore in the new version. `__vmalloc` doesn't have that parameter now and `__vmalloc_node_range` is no longer exported.

```
  CC [M]  /tmp/ndiswrapper-arch/trunk/src/ndiswrapper-1.62/driver/loader.o
/tmp/ndiswrapper-arch/trunk/src/ndiswrapper-1.62/driver/loader.c: In function ‘load_sys_files’:
/tmp/ndiswrapper-arch/trunk/src/ndiswrapper-1.62/driver/loader.c:157:4: error: too many arguments to function ‘__vmalloc’
  157 |    __vmalloc(load_driver->sys_files[i].size,
      |    ^~~~~~~~~
In file included from ./include/asm-generic/io.h:911,
                 from ./arch/x86/include/asm/io.h:375,
                 from ./include/linux/scatterlist.h:9,
                 from ./include/linux/dma-mapping.h:11,
                 from ./include/linux/skbuff.h:31,
                 from ./include/linux/if_ether.h:19,
                 from ./include/uapi/linux/ethtool.h:19,
                 from ./include/linux/ethtool.h:18,
                 from ./include/linux/netdevice.h:37,
                 from /tmp/ndiswrapper-arch/trunk/src/ndiswrapper-1.62/driver/ntoskernel.h:25,
                 from /tmp/ndiswrapper-arch/trunk/src/ndiswrapper-1.62/driver/ndis.h:19,
                 from /tmp/ndiswrapper-arch/trunk/src/ndiswrapper-1.62/driver/loader.c:16:
./include/linux/vmalloc.h:111:14: note: declared here
  111 | extern void *__vmalloc(unsigned long size, gfp_t gfp_mask);
      |              ^~~~~~~~~
make[2]: *** [scripts/Makefile.build:281: /tmp/ndiswrapper-arch/trunk/src/ndiswrapper-1.62/driver/loader.o] Error 1
make[2]: *** Waiting for unfinished jobs....
```

**Comment by FFY00** [comment]
In Linux 5.8, the 3rd argument was removed. It is now always `PAGE_KERNEL_EXEC`.

https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/commit/mm/vmalloc.c?h=next-20200605&id=88dca4ca5a93d2c09e5bbc6a62fbfc3af83c4fca

**Comment by rezso** [comment]
Try this patch:

[kernel-5.8.patch.txt](https://github.com/pgiri/ndiswrapper/files/6032290/kernel-5.8.patch.txt)

**Comment by pgiri** [comment]
Can you test above patch and confirm if it works?

**Comment by tkasozi** [comment]
this patch helped me get the installation complete

**Comment by xtforever** [comment]
ndiswrapper 1.6.3, kernel 5.8 patch applied, compile and install driver works fine. Driver: (FritzStick_64bit_winxp_v061228)
when i modprobe ndiswrapper i get:
 kernel tried to execute NX-protected page - exploit attempt? (uid: 0)

maybe__vmalloc does not allow executeable pages any more?
Kernel: SMP Debian 5.10.24-1~bpo10+1

**Comment by CoolOmar2020** [comment]
> Try this patch:
> 
> [kernel-5.8.patch.txt](https://github.com/pgiri/ndiswrapper/files/6032290/kernel-5.8.patch.txt)

Do you have a patch for 5.13 ??

**Comment by rezso** [comment]
> Do you have a patch for 5.13 ??

No. I have 5.10.18 kernel.

**Comment by CoolOmar2020** [comment]
> > Do you have a patch for 5.13 ??
> 
> No. I have 5.10.18

OK send it but patching with patch command fails do you have other suggestions??

**Comment by CoolOmar2020** [comment]
@rezso where's the patch man?

**Comment by net-wayfarer** [comment]
@CoolOmar2020,
> @rezso where's the patch man?

[The link to the patch was already provided in this same issue. Click here to see the included patch.](https://github.com/pgiri/ndiswrapper/issues/6#issuecomment-784579834)

The included patch does work against [ndiswrapper-1.63](https://sourceforge.net/projects/ndiswrapper/files/stable/) and it does appear to compile successfully against kernel 5.14.

I have gotten the `patch` command to work via the following:
```
patch --no-backup-if-mismatch -p1 -i kernel-5.8.patch.txt
```

**Comment by CoolOmar2020** [comment]
> @CoolOmar2020,
> 
> > @rezso where's the patch man?
> 
> 
> 
> [The link to the patch was already provided in this same issue. Click here to see the included patch.](https://github.com/pgiri/ndiswrapper/issues/6#issuecomment-784579834)
> 
> 
> 
> The included patch does work against [ndiswrapper-1.63](https://sourceforge.net/projects/ndiswrapper/files/stable/) and it does appear to compile successfully against kernel 5.14.
> 
> 
> 
> I have gotten the `patch` command to work via the following:
> 
> ```
> 
> patch --no-backup-if-mismatch -p1 -i kernel-5.8.patch.txt
> 
> ```

I am looking for the 5.10 patch

**Comment by net-wayfarer** [comment]
> > @CoolOmar2020,
> > > @rezso where's the patch man?
> > 
> > 
> > [The link to the patch was already provided in this same issue. Click here to see the included patch.](https://github.com/pgiri/ndiswrapper/issues/6#issuecomment-784579834)
> > The included patch does work against [ndiswrapper-1.63](https://sourceforge.net/projects/ndiswrapper/files/stable/) and it does appear to compile successfully against kernel 5.14.
> > I have gotten the `patch` command to work via the following:
> > ```
> > 
> > patch --no-backup-if-mismatch -p1 -i kernel-5.8.patch.txt
> > ```
> 
> I am looking for the 5.10 patch

Does the said patch not work against 5.10? [There is another variant of this kernel-5.8 patch](https://lists.rpmfusion.org/archives/list/rpmfusion-commits@lists.rpmfusion.org/thread/7D6NFH2IH7FDA35NLHPHWZLK2YTY36QV/). Personally, I do not know of any patches that are specifically for 5.10.

**Comment by CoolOmar2020** [comment]
> > > @CoolOmar2020,
> 
> > > > @rezso where's the patch man?
> 
> > > 
> 
> > > 
> 
> > > [The link to the patch was already provided in this same issue. Click here to see the included patch.](https://github.com/pgiri/ndiswrapper/issues/6#issuecomment-784579834)
> 
> > > The included patch does work against [ndiswrapper-1.63](https://sourceforge.net/projects/ndiswrapper/files/stable/) and it does appear to compile successfully against kernel 5.14.
> 
> > > I have gotten the `patch` command to work via the following:
> 
> > > ```
> 
> > > 
> 
> > > patch --no-backup-if-mismatch -p1 -i kernel-5.8.patch.txt
> 
> > > ```
> 
> > 
> 
> > I am looking for the 5.10 patch
> 
> 
> 
> Does the said patch not work against 5.10? [There is another variant of this kernel-5.8 patch](https://lists.rpmfusion.org/archives/list/rpmfusion-commits@lists.rpmfusion.org/thread/7D6NFH2IH7FDA35NLHPHWZLK2YTY36QV/). Personally, I do not know of any patches that are specifically for 5.10.

@rezso said he has one

**Comment by TBM13** [comment]
> ndiswrapper 1.6.3, kernel 5.8 patch applied, compile and install driver works fine. Driver: (FritzStick_64bit_winxp_v061228) when i modprobe ndiswrapper i get: kernel tried to execute NX-protected page - exploit attempt? (uid: 0)
> 
> maybe__vmalloc does not allow executeable pages any more? Kernel: SMP Debian 5.10.24-1~bpo10+1

Same issue.

**Comment by jcontoso** [comment]
My patches for newer kernels have been merged, It would be nice if others could test it out
